ALTER TABLE public.client_financial_settings
ADD COLUMN IF NOT EXISTS ss_q1 numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ss_q2 numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ss_q3 numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ss_q4 numeric NOT NULL DEFAULT 0;